metadata:
  name: "disallow-stable-tag"
  annotations:
    policies.kyverno.io/category: "customPolicy"
    policies.kyverno.io/description: "The ':test' tag is mutable and can lead to\
      \ unexpected errors if the image changes.  A best practice is to use an immutable\
      \ tag (e.g. v2.3) that maps to a specific version  of an application pod."
apiVersion: "kyverno.io/v1"
kind: "ClusterPolicy"
spec:
  rules:
  - match:
      resources:
        kinds:
        - "Pod"
    name: "require-image-tag"
    validate:
      pattern:
        spec:
          containers:
          - image: "*:*"
      message: "An image tag is required."
  - match:
      resources:
        kinds:
        - "Pod"
    name: "validate-image-tag"
    validate:
      pattern:
        spec:
          containers:
          - image: "!*:stable"
      message: "Using the ':stable' tag is not recommended."